#require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true

Gemspec/RequireMFA:
  Enabled: false

Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true

Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Max: 150

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true

Lint/DeprecatedConstants: # new in 1.8
  Enabled: true

Lint/DuplicateBranch: # new in 1.3
  Enabled: true

Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true

Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true

Lint/DuplicateMethods:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass: # new in 1.3
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInPattern: # new in 1.16
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true

Lint/ItWithoutArgumentsInBlock: # new in 1.59
  Enabled: true

Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true

Lint/LiteralAssignmentInCondition: # new in 1.58
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedCaseRange: # new in 1.53
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true

Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true

Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true

Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true

Lint/RaiseException:
  Enabled: false

Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true

Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true

Lint/RefinementImportMethods: # new in 1.27
  Enabled: true

Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true

Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true
  AllowedMethods:
    - present?
    - blank?
    - presence
    - try
    - try!
    - empty?
    - nil?
    - blank?

Lint/SymbolConversion:
  Enabled: false

Lint/ToEnumArguments: # new in 1.1
  Enabled: true

Lint/TripleQuotes: # new in 1.9
  Enabled: true

Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessRescue: # new in 1.43
  Enabled: true

Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CollectionLiteralLength: # new in 1.47
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 20

Naming/BlockForwarding: # new in 1.24
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: [a, _, id]

Naming/VariableNumber:
  Enabled: true
#  EnforcedStyle: snake_case

#Performance/CollectionLiteralInLoop:
#  Enabled: true
#
#Performance/RangeInclude:
#  Enabled: false
#
#Performance/RedundantEqualityComparisonBlock:
#  Enabled: true

Security/CompoundHash: # new in 1.28
  Enabled: true

Security/IoMethods: # new in 1.22
  Enabled: true

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/Alias:
  Enabled: false
  EnforcedStyle: prefer_alias_method

Style/ArgumentsForwarding: # new in 1.1
  Enabled: true

Style/ArrayIntersect: # new in 1.40
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CollectionCompact: # new in 1.2
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/ComparableClamp: # new in 1.44
  Enabled: true

Style/ConcatArrayLiterals: # new in 1.41
  Enabled: true

Style/DataInheritance: # new in 1.49
  Enabled: true

Style/DirEmpty: # new in 1.48
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true

Style/EmptyHeredoc: # new in 1.32
  Enabled: true

Style/EndlessMethod: # new in 1.8
  Enabled: true

Style/EnvHome: # new in 1.29
  Enabled: true

Style/ExactRegexpMatch: # new in 1.51
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileEmpty: # new in 1.48
  Enabled: true

Style/FileRead: # new in 1.24
  Enabled: true

Style/FileWrite: # new in 1.24
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashConversion: # new in 1.10
  Enabled: true

Style/HashExcept: # new in 1.7
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: consistent

Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true

Style/InPatternThen: # new in 1.16
  Enabled: true

Style/MagicCommentFormat: # new in 1.35
  Enabled: true

Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true

Style/MapToHash: # new in 1.24
  Enabled: true

Style/MapToSet: # new in 1.42
  Enabled: true

Style/MinMaxComparison: # new in 1.42
  Enabled: true

Style/MixinGrouping:
  Enabled: true
  EnforcedStyle: grouped

Style/MultilineInPatternThen: # new in 1.16
  Enabled: true

Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true

Style/NestedFileDirname: # new in 1.26
  Enabled: true

Style/NilLambda: # new in 1.3
  Enabled: true

Style/NumberedParameters: # new in 1.22
  Enabled: true

Style/NumberedParametersLimit: # new in 1.22
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/ObjectThen: # new in 1.28
  Enabled: true

Style/OpenStructUse:
  Enabled: false

Style/OperatorMethodCall: # new in 1.37
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/QuotedSymbols: # new in 1.16
  Enabled: true

Style/RedundantArgument: # new in 1.4
  Enabled: true

Style/RedundantArrayConstructor: # new in 1.52
  Enabled: true

Style/RedundantConstantBase: # new in 1.40
  Enabled: true

Style/RedundantCurrentDirectoryInPath: # new in 1.53
  Enabled: true

Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true

Style/RedundantEach: # new in 1.38
  Enabled: true

Style/RedundantFilterChain: # new in 1.52
  Enabled: true

Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: true

Style/RedundantInitialize: # new in 1.27
  Enabled: true

Style/RedundantLineContinuation: # new in 1.49
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantRegexpArgument: # new in 1.53
  Enabled: true

Style/RedundantRegexpConstructor: # new in 1.52
  Enabled: true

Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true

Style/RedundantStringEscape: # new in 1.37
  Enabled: true

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: mixed

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/ReturnNilInPredicateMethodDefinition: # new in 1.53
  Enabled: true

Style/SelectByRegexp: # new in 1.22
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineDoEndBlock: # new in 1.57
  Enabled: true

Style/StringChars: # new in 1.12
  Enabled: true

Style/SuperWithArgsParentheses: # new in 1.58
  Enabled: true

Style/SwapValues: # new in 1.1
  Enabled: true

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/YAMLFileRead: # new in 1.53
  Enabled: true